### This notebook merges a year of weather data with the stations dataset. 
###   -> change the year in the first cell to explore different years.

1. https://www.ncei.noaa.gov/pub/data/ghcn/daily/by_year
   - look at ranges of years. Note the size of year 1763 vs year 2025 

   <br>

2. https://www.ncei.noaa.gov/pub/data/ghcn/daily/readme-by_year.txt
   - description of each column


<br>

3. https://www.ncei.noaa.gov/pub/data/ghcn/daily/readme.txt
   - go to "III. FORMAT OF DATA FILES (".dly" FILES)" and then "ELEMENT" to see **description of ELEMENTS**.

<br>


4. https://www.ncei.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt
   - we can merge the station dataset for metadata on station ID

In [ ]:
import tempfile
import pandas as pd
import urllib.request
import os

# ----------------------------- weather by year X dataset --------------------------------

# raw csv had no header row.
cols = ['STATION', 'DATE', 'ELEMENT', 'VALUE', 'M_FLAG', 'Q_FLAG', 'S_FLAG', 'OBS_TIME']
url = "https://www.ncei.noaa.gov/pub/data/ghcn/daily/by_year/2015.csv.gz"   # CHANGE 1763 to whatever year to explore

# Note this (1 years worth of data) takes like a minute to load
with tempfile.NamedTemporaryFile(suffix=".csv.gz", delete=False) as tmp:   
    urllib.request.urlretrieve(url, tmp.name)
    weather_yearX = pd.read_csv(tmp.name, header=None, names=cols, compression='gzip')

print(f'temp file location: {tmp.name}')
os.remove(tmp.name)    # cleanup handled here

temp file location: C:\Users\bsenc\AppData\Local\Temp\tmp_nx_z1ov.csv.gz

In [ ]:
# ----------------------------- station dataset --------------------------------

url = "https://www.ncei.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt"
colwidths = [(0,11), (12,20), (21,30), (31,37), (38,40), (41,71), (72,75), (76,79), (80,85)]
cols = ['ID', 'LATITUDE', 'LONGITUDE', 'ELEVATION', 'STATE', 'NAME', 'GSN FLAG', 'HCN/CRN FLAG', 'WMO ID']

with tempfile.NamedTemporaryFile(suffix=".txt", delete=False) as tmp:
    urllib.request.urlretrieve(url, tmp.name)
    stations = pd.read_fwf(tmp.name, colspecs=colwidths, header=None, names=cols)

print(f'temp file location: {tmp.name}')
os.remove(tmp.name)

temp file location: C:\Users\bsenc\AppData\Local\Temp\tmpu3r5p7t1.txt

In [ ]:
weather_yearX.head()

       STATION      DATE ELEMENT  VALUE  M_FLAG Q_FLAG S_FLAG  OBS_TIME
0  ITE00100554  17630101    TMAX    -36     NaN    NaN      E       NaN
1  ITE00100554  17630101    TMIN    -50     NaN    NaN      E       NaN
2  ITE00100554  17630102    TMAX    -26     NaN    NaN      E       NaN
3  ITE00100554  17630102    TMIN    -40     NaN    NaN      E       NaN
4  ITE00100554  17630103    TMAX     -9     NaN    NaN      E       NaN

In [ ]:
stations.head()

,ID,LATITUDE,LONGITUDE,ELEVATION,STATE,NAME,GSN FLAG,HCN/CRN FLAG,WMO ID
0,ACW00011604,17.1167,-61.7833,10.1,NaN,ST JOHNS COOLIDGE FLD,NaN,NaN,NaN
1,ACW00011647,17.1333,-61.7833,19.2,NaN,ST JOHNS,NaN,NaN,NaN
2,AE000041196,25.3330,55.5170,34.0,NaN,SHARJAH INTER. AIRP,GSN,NaN,41196.0
3,AEM00041194,25.2550,55.3640,10.4,NaN,DUBAI INTL,NaN,NaN,41194.0
4,AEM00041217,24.4330,54.6510,26.8,NaN,ABU DHABI INTL,NaN,NaN,41217.0

In [ ]:
merged = weather_yearX.merge(stations, left_on='STATION', right_on='ID', how='left')

In [ ]:
merged.info()

<class 'pandas.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   STATION       730 non-null    str
 1   DATE          730 non-null    int64
 2   ELEMENT       730 non-null    str
 3   VALUE         730 non-null    int64
 4   M_FLAG        0 non-null      float64
 5   Q_FLAG        16 non-null     str
 6   S_FLAG        730 non-null    str
 7   OBS_TIME      0 non-null      float64
 8   ID            730 non-null    str
 9   LATITUDE      730 non-null    float64
 10  LONGITUDE     730 non-null    float64
 11  ELEVATION     730 non-null    float64
 12  STATE         0 non-null      str
 13  NAME          730 non-null    str
 14  GSN FLAG      0 non-null      str
 15  HCN/CRN FLAG  0 non-null      str
 16  WMO ID        0 non-null      float64
dtypes: float64(6), int64(2), str(9)
memory usage: 97.1 KB